[bar.default]
margin_edge = 5
margin_ends = 9
thickness = 24

[dock]
auto_hide = true
enabled = true
reserve_space = false

[location]
address = "Sao Paulo"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 957.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[theme]
builtin = "Noctalia"
mode = "dark"
source = "wallpaper"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "foot", "gtk3", "gtk4", "hyprland", "qt", "starship" ]
    community_ids = [ "discord", "yazi", "hyprtoolkit" ]

[wallpaper]
directory = "/home/victor/Imagens/Wallpapers"

    [wallpaper.default]
    path = "/home/victor/Imagens/Wallpapers/wallpaper.jpg"

    [wallpaper.last]
    path = "/home/victor/Imagens/Wallpapers/wallpaper.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/victor/Imagens/Wallpapers/wallpaper.jpg"

